suda:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20050904@Aa
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tA6YYStxGDe7XhMs6uX
    access-key-secret: LLvyGp8CkVpbq6W3RP2GbzPSnrNMlX
    bucket-name: kamtenbucket-sky
  redis:
    host: localhost
    port: 6380
    password: 123456
    database: 1
  wechat:
    app-id: wxcf8208fdc6c87cfc
    secret: 24d6aefe839bb95a2b412ce66ada6ce9
    mchid: 1561414331
    mchSecret: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath:
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:/path/to/your/apiclient_cert.pem
    notifyUrl: https://62575e77.r30.cpolar.top/notify/paySuccess
    refundNotifyUrl:
